# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    grafana.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: marvin <marvin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/02/18 22:41:45 by marvin            #+#    #+#              #
#    Updated: 2021/02/18 22:41:46 by marvin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata: 
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels: 
    app: grafana
  name: grafana-service
spec: 
  ports: 
    -
      port: 3000
  selector: 
    app: grafana
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: grafana
  name: grafana-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: grafana
  template: 
    metadata: 
      labels: 
        app: grafana
    spec: 
      containers: 
        - 
          image: grafana_service
          name: grafana
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
