# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    phpmyadmin.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: marvin <marvin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/02/18 22:42:40 by marvin            #+#    #+#              #
#    Updated: 2021/02/18 22:42:41 by marvin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata: 
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels: 
    app: phpmyadmin
  name: phpmyadmin-service
spec: 
  ports: 
    -
      port: 5000
      name: phpmyadmin
  selector: 
    app: phpmyadmin
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: phpmyadmin
  name: phpmyadmin-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: phpmyadmin
  template: 
    metadata: 
      labels: 
        app: phpmyadmin
    spec: 
      restartPolicy: Always
      containers: 
        - 
          image: phpmyadmin_service
          name: phpmyadmin
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
